server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: mediabot
  pipeline_stages:
  - json:
      expressions:
        timestamp: timestamp
        level: level
        instance: instance
        action: action
  - labels:
      level:
      instance:
      action:
  static_configs:
  - targets:
      - localhost
    labels:
      job: mediabot
      __path__: /mediabot-logs/*.log*
