"""create language table

Revision ID: c4c2973d8cf1
Revises: 48283bd81834
Create Date: 2024-03-13 00:06:50.666655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4c2973d8cf1'
down_revision: Union[str, None] = '48283bd81834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('instance_origin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instance_origin'], ['instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_id'), 'language', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_language_id'), table_name='language')
    op.drop_table('language')
    # ### end Alembic commands ###
